export interface Project {
  slug: string;
  name: string;
  tagline: string;
  category: "AI" | "Web" | "Mobile";
  problem: string;
  approach: string;
  stack: string[];
  metric: string;
  // Brand color used for the project card's poster gradient.
  color: string;
  liveUrl?: string;
  repoUrl?: string;
  status: "Live" | "In development";
  // TODO: replace with real version tags / ship dates from each project's actual release history.
  shipped: string;
}

export const projects: Project[] = [
  {
    slug: "blog-assist",
    name: "Blog Assist",
    tagline:
      "An autonomous agent that researches, writes, and publishes blog content on a schedule",
    category: "AI",
    problem: "Content teams burn hours per post on research and drafting.",
    approach:
      "Multi-threaded scheduler running independently of Streamlit's rerun cycle; dual LLM support (Gemini + OpenAI); WordPress publishing integration.",
    stack: ["Python", "Streamlit", "Gemini API", "OpenAI API", "WordPress REST API"],
    metric: "100+ daily active users",
    color: "#5B6CFF",
    liveUrl: "https://blogassist.streamlit.app",
    status: "Live",
    shipped: "v1.0 — 2024",
  },
  {
    slug: "hireultra",
    name: "HireUltra",
    tagline:
      "AI-powered candidate sourcing and match scoring across LinkedIn and the open web",
    category: "AI",
    problem: "Manual resume screening doesn't scale past a handful of roles.",
    approach:
      "Tiered sourcing (free DuckDuckGo → Serper X-Ray search → LinkedIn API), JD parsing, match scoring with visual tags.",
    stack: ["Python", "Streamlit", "Serper API", "PyPDF", "Pandas"],
    metric: "87% match accuracy",
    color: "#12B3A6",
    liveUrl: "https://hireultra.streamlit.app",
    status: "Live",
    shipped: "v1.0 — 2024",
  },
  {
    slug: "transpent",
    name: "Transpent",
    tagline:
      "Offline-first ledger app for small shop owners tracking customer credit and supplier bills",
    category: "Mobile",
    problem:
      "Small, often women-led, shops in low-connectivity areas have no reliable way to track credit without internet access.",
    approach:
      "Local-first storage via Room/SQLite, MVVM architecture, CSV export.",
    stack: ["Kotlin", "Jetpack Compose", "Room/SQLite"],
    metric: "Distributed via GitHub releases, active development",
    color: "#E8A23B",
    // TODO: add the real repo URL once confirmed.
    status: "In development",
    shipped: "v0.x — In development",
  },
  {
    slug: "mimries",
    name: "Mimries",
    tagline:
      "An edge-native platform for instant, branded guest galleries at live events — no app download required",
    category: "Web",
    problem:
      "Event hosts want a shared, curated photo experience without forcing guests through app installs.",
    approach:
      "Guests submit via WhatsApp or direct upload; admin curates; gallery updates live. Built on Cloudflare's edge (Workers/Hono.js, D1, R2), Supabase auth, Next.js admin portal, vanilla JS guest app. English and Hindi supported.",
    stack: ["Cloudflare Workers", "Hono.js", "D1", "R2", "Supabase", "Next.js"],
    metric: "Validated through a live production deployment",
    color: "#FF5436",
    liveUrl: "https://mimries.com",
    status: "Live",
    shipped: "v1.0 — 2025",
  },
  {
    slug: "swovid",
    name: "SwoVid",
    tagline:
      "An AI content authenticity platform that detects whether images and videos are AI-generated or human-made — right inside your browser",
    category: "AI",
    problem:
      "There's no accessible, ambient tool to verify whether the content you see online was made by a human or generated by AI.",
    approach:
      "A layered detection stack reading every major provenance standard at once — C2PA cryptographic credentials, IPTC/EXIF metadata, Stable Signature and Video Seal watermarks, and a proprietary ONNX model. Delivered as a Chrome extension, web app, and mobile app from one Turborepo monorepo, with an ambient badge on every image and an honest five-state verdict system.",
    stack: ["Preact", "TypeScript", "C2PA", "ONNX Runtime", "Cloudflare Workers", "Turborepo"],
    metric: "Multi-standard detection — C2PA, IPTC, EXIF, watermarks",
    color: "#7C4DFF",
    status: "In development",
    shipped: "V1 — In development",
  },
  {
    slug: "preschool-hub",
    name: "Preschool Hub",
    tagline:
      "A multi-tenant school management platform connecting preschools, teachers, and parents across one shared daily record",
    category: "Mobile",
    problem:
      "Most preschools and daycares in India still run on WhatsApp groups or paper diaries — no structured record of a child's day and no visibility for school owners.",
    approach:
      "A single Flutter codebase serving five roles across Android, iOS, and Web, with each school an isolated, white-labeled tenant on shared Firebase infrastructure. School-code login re-themes the UI live; role-based routing via go_router; DPDP Act 2023 consent built into the UX; privileged operations server-side through Cloud Functions.",
    stack: ["Flutter", "Dart", "Firebase", "Firestore", "Riverpod", "go_router"],
    metric: "Five roles, one codebase — Android, iOS & Web",
    color: "#00A878",
    status: "In development",
    shipped: "Phase 1 — In development",
  },
];
